steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', '$LOCATION-docker.pkg.dev/$PROJECT_ID/emirapp/emirapp', '.' ]
- name: 'gcr.io/cloud-builders/kubectl'
  id: Deploy
  args:
  - 'replace'
  - '-f'
  - './k8s/deployment.yaml'
  - '-n'
  - 'emirapp'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-c'
    - 'CLOUDSDK_CONTAINER_CLUSTER=playground'
images:
- '$LOCATION-docker.pkg.dev/$PROJECT_ID/emirapp/emirapp'
